### ISSUE TITLE
pnpm dev: tsx problem with @fastify/autoload

### ISSUE THREAD

**Issue by etino** [davipon/fastify-esbuild#13]
Hello, I've found this interesting repository from this dev.to post [Better Backend DX: Fastify + ESBuild = ⚡️](https://dev.to/davipon/better-backend-dx-fastify-esbuild--50ep)

After clone it I found that `tsx` that in used in the `pnpm dev` script is not installed.

After having installed it with `pnpm add -D tsx`, when I run the command `pnpm dev` I get the error below.

```bash
[10:29:11.490] ERROR: @fastify/autoload cannot import plugin at 'C:\SVILUPPO\sandbox\fastify-esbuild\src\plugins\sensible.ts'. 
To fix this error compile TypeScript to JavaScript or use 'ts-node' to run your app.
```

The problem doesn't occur if I run `pnpm build` and then `node build/index.js`.

It seems a problem of `tsx`.  

Do you have any insight to resolve the problem?

Dependency list

```
$ pnpm list
           Legend: production dependency, optional only, dev only

fastify-esbuild@0.1.1 C:\SVILUPPO\sandbox\fastify-esbuild

dependencies:
@fastify/autoload 5.0.0
@fastify/sensible 5.1.0
@fastify/swagger 7.4.0
fastify 4.1.0
fastify-plugin 3.0.1

devDependencies:
@commitlint/cli 17.0.3                   esbuild-plugin-pino 1.2.1                nodemon 2.0.18
@commitlint/config-conventional 17.0.3   eslint 8.18.0                            pino 8.1.0
@commitlint/cz-commitlint 17.0.3         eslint-config-prettier 8.5.0             pino-pretty 8.1.0
@types/node 18.0.0                       eslint-plugin-prettier 4.1.0             prettier 2.7.1
@typescript-eslint/eslint-plugin 5.30.0  husky 8.0.1                              standard-version 9.5.0
@typescript-eslint/parser 5.30.0         inquirer 8.2.4                           thread-stream 1.0.0
commitizen 4.2.4                         json-schema-to-ts 2.5.3                  tsx 3.7.1
esbuild 0.14.48                          lint-staged 13.0.3                       typescript 4.7.4
```

**Comment by davipon** [comment]
Hi @etino, I thought I accidentally pushed the experimental commit.

I'll open a PR at `@fastify/autoload` to add `tsx` support.
I've discussed with the `tsx` author about detecting TS runtime, you can check here: https://github.com/esbuild-kit/tsx/issues/49

Please use `nodemon + esbuild` for dev, I'll update this repo once `@fastify/autoload` supports `tsx`.

**Comment by etino** [comment]
> @etino , this repo has updated to use `tsx` instead of `nodemon`, which brings a great DX when developing a Fastify project with TypeScript.
> 
> Please try it and let me know if you have any ideas or problems. Thanks.

Awesome! It worked well. 
Thank you @davipon
